version: "3.8"

services:
  database:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_DATABASE: mavizcare
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  app:
    build: .
    container_name: mavizcare
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: k8s
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/mavizcare
    ports:
      - "8080:8080"

volumes:
  db_data:
