apiVersion: v1
kind: Secret
metadata:
<<<<<<< HEAD
  name: {{ include "springboot.appname" . }}
=======
  name: {{ include "springboot.fullname" . }}
>>>>>>> main
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_HOST: "{{ include "springboot.dbname" . }}"
  SPRING_DATASOURCE_PORT: "{{ .Values.mariadb.port | default 3306 }}"
  SPRING_DATASOURCE_DATABASE: "{{ .Values.mariadb.database }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.mariadb.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.mariadb.password }}"
