apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot.dbname" . }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  MARIADB_USER: {{ .Values.mariadb.username | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
