apiVersion: v1
kind: Service

metadata:
  name: {{ include "springboot.dbname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

spec:
  clusterIP: None
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  
  selector:
    app.kubernetes.io/name: {{ include "springboot.dbname" . }}
    app.kubernetes.io/component: db

