apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "springboot.dbname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

spec:
  serviceName: {{ include "springboot.dbname" . }}

  replicas: {{ .Values.mariadb.replicas }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "springboot.dbname" . }}
      app.kubernetes.io/component: db

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "springboot.dbname" . }}
        app.kubernetes.io/component: db

    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}

          ports:
            - name: mariadb
              containerPort: 3306

          envFrom:
            - secretRef:
                name: {{ include "springboot.dbname" . }}
            {{- if .Values.mariadb.envConfigMap }}
            - configMapRef:
                name: {{ include "springboot.dbname" . }}
            {{- end }}

          {{- with .Values.mariadb.probes.liveness }}
          {{- if .enabled }}
          livenessProbe:
            exec:
              command:
            {{ toYaml .exec.command | nindent 14 }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}

          {{- with .Values.mariadb.probes.readiness }}
          {{- if .enabled }}
          readinessProbe:
            exec:
              command:
            {{ toYaml .exec.command | nindent 14 }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}

          {{- with .Values.mariadb.probes.startup }}
          {{- if .enabled }}
          startupProbe:
            exec:
              command:
            {{ toYaml .exec.command | nindent 14 }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}

          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mariadb.persistence.size }}
        {{- if .Values.mariadb.persistence.storageClass }}
        storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
        {{- end }}
