name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/mavizcare

jobs:
  gradle:
    name: Build Spring Boot JAR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      sha: ${{ steps.sha.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Expose commit SHA
        id: sha
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          VERSION=${{ steps.setver.outputs.version }}
          git tag -f "v$VERSION"
          git push --force origin "v$VERSION"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build JAR
        run: ./gradlew -Pversion=${GITHUB_SHA} bootJar --no-daemon

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mavizcare-jar
          path: build/libs/mavizcare-${GITHUB_SHA}.jar

  docker:
    name: Build & Push Docker Image
    needs: gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Expose SHA
        run: echo "SHA=${{ needs.gradle.outputs.sha }}" >> $GITHUB_ENV

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: mavizcare-jar
          path: jar

      - name: Resolve JAR file
        run: echo "JAR_FILE=$(ls jar/*.jar)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mavizcare:${{ env.SHA }}
            ghcr.io/${{ github.repository_owner }}/mavizcare:latest
          build-args: |
            JAR_FILE=${{ env.JAR_FILE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
